# Generated by Django 3.2.16 on 2022-10-07 17:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcompany',
            name='companyEmail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='rentalcompany',
            name='companyPhoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
