# Generated by Django 3.2.16 on 2022-10-08 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carRental', '0002_auto_20221007_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalcompany',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carRental', to=settings.AUTH_USER_MODEL),
        ),
    ]
