# Generated by Django 3.2.16 on 2022-10-12 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0003_rentalcompany_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturerName', models.CharField(blank=True, default='', max_length=100)),
                ('manufacturerLogo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='rentalcompany',
            name='companyLogo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carModel', models.CharField(default='', max_length=100)),
                ('type', models.CharField(choices=[('MINI', 'mini'), ('Medium', 'medium'), ('MID_RANGE', 'mid-range'), ('SEDAN', 'sedan'), ('SUV', 'suv')], default='', max_length=100)),
                ('transmission', models.CharField(choices=[('MANUAL', 'manual'), ('AUTOMATIC', 'automatic')], default='', max_length=100)),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carRental.manufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='rentalcompany',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carRental.car'),
        ),
    ]
