# Generated by Django 3.2.16 on 2022-10-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0004_auto_20221012_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
