# Generated by Django 3.2.16 on 2022-10-23 11:50

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0006_auto_20221012_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumerFirstName', models.CharField(default='', max_length=80)),
                ('costumerLastName', models.CharField(default='', max_length=80)),
                ('costumerEmail', models.EmailField(default='', max_length=254)),
                ('costumerPhoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('costumerAFM', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceToStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeToStart', models.CharField(choices=[('Home', 'home'), ('Airport', 'airport'), ('KTEL', 'ktel')], max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('MANUAL', 'manual'), ('AUTOMATIC', 'automatic')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('MINI', 'mini'), ('Medium', 'medium'), ('MID_RANGE', 'mid-range'), ('SEDAN', 'sedan'), ('SUV', 'suv')], default='', max_length=15),
        ),
        migrations.RemoveField(
            model_name='rentalcompany',
            name='car',
        ),
        migrations.AddField(
            model_name='rentalcompany',
            name='car',
            field=models.ManyToManyField(to='carRental.Car'),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('finishDate', models.DateField()),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carRental.car')),
                ('costumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carRental.costumer')),
                ('placeToStart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carRental.placetostart')),
                ('rentalCompany', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carRental.rentalcompany')),
            ],
        ),
        migrations.AddField(
            model_name='rentalcompany',
            name='costumer',
            field=models.ManyToManyField(to='carRental.Costumer'),
        ),
        migrations.AddField(
            model_name='rentalcompany',
            name='placeToStart',
            field=models.ManyToManyField(to='carRental.PlaceToStart'),
        ),
    ]
