# Generated by Django 3.0.5 on 2022-11-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0009_auto_20221108_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='insurance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='tank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
