# Generated by Django 3.0.5 on 2022-11-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0010_auto_20221108_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
