# Generated by Django 3.0.5 on 2022-11-13 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0012_auto_20221113_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='costumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carRental.Costumer'),
        ),
    ]
