# Generated by Django 3.0.5 on 2022-11-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0013_auto_20221113_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='carId',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='costumerID',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
