# Generated by Django 3.0.5 on 2022-11-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0014_auto_20221114_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='carId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='costumerID',
            field=models.IntegerField(null=True),
        ),
    ]
