# Generated by Django 3.0.5 on 2022-11-17 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0015_auto_20221114_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='profilePic',
            field=models.ImageField(blank=True, default='avatar-g90d8d966e_640.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='rental',
            name='carModel',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='customerName',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rentalCompany',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='carRental.RentalCompany'),
        ),
    ]
