# Generated by Django 3.0.5 on 2022-11-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0018_auto_20221120_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canceledorders',
            name='carId',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='canceledorders',
            name='costumerID',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
