# Generated by Django 3.0.5 on 2022-11-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0019_auto_20221120_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarToDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carId', models.CharField(max_length=70, null=True)),
            ],
        ),
    ]
